[tool.poetry]
name = "python-cheatsheet"
version = "0.1.0"
description = ""
authors = ["'Carlos <'carlos.w.montecinos@gmail.com'>"]

[tool.poetry.dependencies]
python = "^3.7"
notedown = "^1.5"
jupyter = "^1.0"

[tool.poetry.dev-dependencies]
